### ISSUE TITLE
Have you finished packing swift framework with cocoapod packge?

### ISSUE THREAD

**Issue by doreamongit** [MaximeLM/TestSwiftImport#1]
Hi Maxime Le Moine,Have you finished packing swift framework with cocoapod packge?I saw your message on https://github.com/CocoaPods/CocoaPods/issues/7594,and found your project.I download your project,run pod package TestLib.podspec --force ,I found an error:
/var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/Pods/TestLib/TestLib/TestObject.m:9:9: fatal error: 'TestLib/TestLib-Swift.h' file not found
    #import <TestLib/TestLib-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    
    Ditto build/TestLib.swiftmodule/x86_64.swiftmodule /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/build/Pods.build/Release/TestLib.build/Objects-normal/x86_64/TestLib.swiftmodule
        cd /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/Pods
        /usr/bin/ditto -rsrc /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/build/Pods.build/Release/TestLib.build/Objects-normal/x86_64/TestLib.swiftmodule /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/Pods/build/TestLib.swiftmodule/x86_64.swiftmodule
    
    Ditto build/TestLib.swiftmodule/x86_64.swiftdoc /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/build/Pods.build/Release/TestLib.build/Objects-normal/x86_64/TestLib.swiftdoc
        cd /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/Pods
        /usr/bin/ditto -rsrc /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/build/Pods.build/Release/TestLib.build/Objects-normal/x86_64/TestLib.swiftdoc /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/Pods/build/TestLib.swiftmodule/x86_64.swiftdoc
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileC /var/folders/nk/s7_m6znn1bz31lz143z43m1c0000gn/T/cocoapods-ov0hb5bz/build/Pods.build/Release/TestLib.build/Objects-normal/x86_64/TestObject.o TestLib/TestLib/TestObject.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)

Do you have any idea?Thanks!

**Comment by MaximeLM** [comment]
Hi, the issue you are mentioning is still opened. You can use the following code as a workaround:
```
#if __has_include("TestLib-Swift.h")
    #import "TestLib-Swift.h"
#else
    #import <TestLib/TestLib-Swift.h>
#endif
```
